// src/utils/databaseExport.ts
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { SQLiteDatabase, openDatabaseAsync } from 'expo-sqlite';

/**
 * Получает список пользовательских таблиц (без системных)
 */
const getTableNames = async (db: SQLiteDatabase): Promise<string[]> => {
  const result = await db.getAllAsync<{ name: string }>(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';"
  );
  return result.map(row => row.name);
};

/**
 * Получает SQL-запрос CREATE TABLE для указанной таблицы
 */
const getCreateTableSQL = async (db: SQLiteDatabase, tableName: string): Promise<string> => {
  const result = await db.getFirstAsync<{ sql: string }>(
    `SELECT sql FROM sqlite_master WHERE type='table' AND name = ?;`,
    [tableName]
  );
  return result?.sql || '';
};

/**
 * Экранирует строку для SQL (защищает от инъекций и ломает кавычки)
 */
const escapeSqlString = (str: string): string => {
  return str.replace(/'/g, "''");
};

/**
 * Генерирует INSERT-запросы для всех строк таблицы
 */
const exportTableToInserts = async (db: SQLiteDatabase, tableName: string): Promise<string[]> => {
  const rows = await db.getAllAsync(`SELECT * FROM ${tableName}`);
  if (rows.length === 0) return [];

  return rows.map(row => {
    const columns = Object.keys(row);
    const values = columns.map(col => {
      const val = row[col];
      if (val === null) return 'NULL';
      if (typeof val === 'string') return `'${escapeSqlString(val)}'`;
      if (typeof val === 'boolean') return val ? '1' : '0';
      return String(val);
    });
    return `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES (${values.join(', ')});`;
  });
};

/**
 * Генерирует полный SQL-дамп базы данных
 */
export const generateFullDump = async (): Promise<string> => {
  const db = await openDatabaseAsync('test.db');

  let dump = '-- Full SQL Dump generated by Expo App\n';
  dump += '-- https://docs.expo.dev/versions/latest/sdk/sqlite/\n\n';

  // Отключаем внешние ключи на время импорта
  dump += 'PRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n\n';

  const tables = await getTableNames(db);

  for (const table of tables) {
    // CREATE TABLE
    const createSQL = await getCreateTableSQL(db, table);
    if (createSQL) {
      dump += `${createSQL};\n\n`;
    }

    // INSERT данные
    const inserts = await exportTableToInserts(db, table);
    if (inserts.length > 0) {
      dump += inserts.join('\n') + '\n\n';
    }
  }

  dump += 'COMMIT;\nPRAGMA foreign_keys=ON;\n';

  return dump;
};

/**
 * Экспортирует дамп как .sql файл и предлагает поделиться
 */
export const exportFullDatabaseDump = async () => {
  try {
    const sqlDump = await generateFullDump();
    const fileName = `btracker_dump_${new Date().toISOString().split('T')[0]}.sql`;
    const uri = `${FileSystem.documentDirectory}${fileName}`;

    await FileSystem.writeAsStringAsync(uri, sqlDump, {
      encoding: FileSystem.EncodingType.UTF8,
    });

    await Sharing.shareAsync(uri, {
      mimeType: 'text/plain',
      dialogTitle: 'Экспорт полной резервной копии (SQL)',
    });
  } catch (error) {
    console.error('❌ Ошибка при создании дампа:', error);
    alert('Не удалось создать резервную копию базы данных');
  }
};